# conda install conda-devenv -c conda-forge
# conda devenv

name: mlops-py312

channels:
  - defaults

dependencies:
  - python=3.12
  - pip=24.3.1
  - pip:
    # format
    - pre-commit==3.7.0
    - black==24.3.0
    - isort==5.13.2
  - attrs=24.2.0
  - mypy=1.11.2
  - mypy_extensions=1.0.0

environment:
  PYTHONPATH:
    - {{ root }}
    - {{ root }}/src
