# conda install conda-devenv -c conda-forge
# conda devenv

name: mlops-py312

channels:
  - defaults

dependencies:
  - python=3.12
  - pip=24.0.0
  - pip:
    # format
    - pre-commit==3.7.0
    - black==24.3.0
    - isort==5.13.2

environment:
  PYTHONPATH:
    - {{ root }}
    - {{ root }}/src
