_wandb:
    value:
        cli_version: 0.19.4
        m:
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 50
                - 53
                - 55
                - 100
                - 103
                - 105
            "2":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 50
                - 53
                - 55
                - 100
                - 103
                - 105
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.12.3
            "5": 0.19.4
            "6": 4.48.0
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
input_size:
    value: 4
lr:
    value: 0.0005
num_classes:
    value: 2
